/* Generated by AN DISI Unibo */ 
package it.unibo.ctx_demo2SonarB;
import it.unibo.qactors.QActorContext;
import java.io.InputStream;
import alice.tuprolog.SolveInfo;
import alice.tuprolog.Term;
import alice.tuprolog.Var;
 
import it.unibo.is.interfaces.IBasicEnvAwt;
import it.unibo.is.interfaces.IIntent;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;

public class MainCtx_demo2SonarB   {
private IBasicEnvAwt env; 
private it.unibo.qactor.robot.RobotActor robot; 
 
 	
/*
* ----------------------------------------------
* MAIN
* ----------------------------------------------
*/
 
	public static void main(String[] args) throws Exception{
			IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
			it.unibo.qactors.QActorUtils.setRobotBase("nano0" );  
		    String webDir = null;
			QActorContext.initQActorSystem(
				"ctx_demo2sonarb", "./srcMore/it/unibo/ctx_demo2SonarB/demo2sys.pl", 
				"./srcMore/it/unibo/ctx_demo2SonarB/sysRules.pl", outEnvView,webDir, false);
 	}
 	
}
