/* Generated by AN DISI Unibo */ 
package it.unibo.qrdemo1robot;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

//
public class Qrdemo1robot extends AbstractQrdemo1robot { 
	public Qrdemo1robot(String actorId, QActorContext myCtx, IOutputEnvView outEnvView ) throws Exception{
		super(actorId,myCtx,outEnvView ,it.unibo.qactors.QActorUtils.robotBase );
	}
}
