/* Generated by AN DISI Unibo */ 
package it.unibo.qrdemo0robot;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

//
public class Qrdemo0robot extends AbstractQrdemo0robot { 
	public Qrdemo0robot(String actorId, QActorContext myCtx, IOutputEnvView outEnvView ) throws Exception{
		super(actorId,myCtx,outEnvView ,it.unibo.qactors.QActorUtils.robotBase );
	}
}
