/* Generated by AN DISI Unibo */ 
package it.unibo.qrdemo2robot;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

//
public class Qrdemo2robot extends AbstractQrdemo2robot { 
	public Qrdemo2robot(String actorId, QActorContext myCtx, IOutputEnvView outEnvView ) throws Exception{
		super(actorId,myCtx,outEnvView ,it.unibo.qactors.QActorUtils.robotBase );
	}
}
