/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qademo2console;
import it.unibo.is.interfaces.IActivity;
import it.unibo.is.interfaces.IIntent;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Qademo2console extends AbstractQademo2console implements IActivity { 
	public Qademo2console(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	protected void addInputPanel(int size){
	}

	public void addCmd(){
		outEnvView.getEnv().addCmdPanel("START", new String[]{"start"}, this);
		outEnvView.getEnv().addCmdPanel("ALARM", new String[]{"alarm"}, this);
	 }
	 public void execAction(String cmd) {
		 this.emit("local_inputcmd", "usercmd("+cmd+")");
	 }
	@Override
	public void execAction() {
		// TODO Auto-generated method stub
		
	}
	@Override
	public void execAction(IIntent input) {
		// TODO Auto-generated method stub
		
	}
	@Override
	public String execActionWithAnswer(String cmd) {
		// TODO Auto-generated method stub
		return null;
	}
}
