/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qapasonarb;
import java.io.BufferedReader;

import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Qapasonarb extends AbstractQapasonarb { 
	protected BufferedReader readerC;
	
	public Qapasonarb(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	public void startSonarC(){
  		try {
  			println("startSonarC"   );
			Process p = Runtime.getRuntime().exec("sudo ./SonarAlone");
			readerC   = new BufferedReader(new java.io.InputStreamReader(p.getInputStream()));
			println("Process in C STARTED "  +  readerC);
		} catch (Exception e) {
 			e.printStackTrace();
		}		
	}	
	public void getDistanceFromSonar(){
		try {
			String dist = readerC.readLine();			
			println("getDistanceFromSonar " + dist  );
			this.addRule("d("+dist+")");
		} catch (Exception e) {
 			e.printStackTrace(); 
		}
	}	
}
