/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qastep2console;
import it.unibo.baseEnv.basicgui.input.CmdPanel;
import it.unibo.is.interfaces.IActivity;
import it.unibo.is.interfaces.IIntent;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Qastep2console extends AbstractQastep2console implements IActivity { 
	private CmdPanel start = new CmdPanel("START", new String[]{"start"}, this);
	private CmdPanel alarm = new CmdPanel("ALARM", new String[]{"alarm"}, this);
	private CmdPanel user = new CmdPanel("USER", new String[]{"user"}, this);
	private CmdPanel comands = new CmdPanel("CMD", new String[]{"left","rforward","right","stop"}, this);
	private CmdPanel autonomus = new CmdPanel("AUTONOMUS", new String[]{"autonomus"}, this);
	private boolean autoB = true;
	
	public Qastep2console(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	protected void addInputPanel(int size){
	}

	public void addCmd(){
		if(autoB)
		{
			outEnvView.getEnv().addPanel(start);
			outEnvView.getEnv().addPanel(alarm);
			outEnvView.getEnv().addPanel(user);
		}
		else {
			outEnvView.getEnv().addPanel(alarm);
			outEnvView.getEnv().addPanel(comands);
			outEnvView.getEnv().addPanel(autonomus);
		}

	 }
	public void removeCmd(){
		if(!autoB)
		{
			outEnvView.getEnv().removePanel(start);
			outEnvView.getEnv().removePanel(alarm);
			outEnvView.getEnv().removePanel(user);
		}
		else {
			outEnvView.getEnv().removePanel(alarm);
			outEnvView.getEnv().removePanel(comands);
			outEnvView.getEnv().removePanel(autonomus);
		}

	 }
	 public void execAction(String cmd) {
		 if(cmd.equals("user"))
		 {
			 autoB=false;
			 removeCmd();
			 addCmd();
		 }
		 else if(cmd.equals("autonomus"))
		 {
			 autoB=true;
			 removeCmd();
			 addCmd();
		 }
		 this.emit("local_inputcmd", "usercmd("+cmd+")");
	 }
	@Override
	public void execAction() {
		// TODO Auto-generated method stub
		
	}
	@Override
	public void execAction(IIntent input) {
		// TODO Auto-generated method stub
		
	}
	@Override
	public String execActionWithAnswer(String cmd) {
		// TODO Auto-generated method stub
		return null;
	}
}
