/* Generated by AN DISI Unibo */ 
package it.unibo.cxt_demo0SonarA;
import it.unibo.qactors.QActorContext;
import java.io.InputStream;
import alice.tuprolog.SolveInfo;
import alice.tuprolog.Term;
import alice.tuprolog.Var;
 
import it.unibo.is.interfaces.IBasicEnvAwt;
import it.unibo.is.interfaces.IIntent;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;

public class MainCxt_demo0SonarA   {
private IBasicEnvAwt env; 
private it.unibo.qactor.robot.RobotActor robot; 
 
 	
/*
* ----------------------------------------------
* MAIN
* ----------------------------------------------
*/
 
	public static void main(String[] args) throws Exception{
			IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
			it.unibo.qactors.QActorUtils.setRobotBase("nano0" );  
			it.unibo.is.interfaces.IBasicEnvAwt env=new it.unibo.baseEnv.basicFrame.EnvFrame( 
			"Env_cxt_demo0SonarA",java.awt.Color.blue , java.awt.Color.black );
		env.init();
		outEnvView = env.getOutputEnvView();
		    String webDir = null;
			QActorContext.initQActorSystem(
				"cxt_demo0sonara", "./srcMore/it/unibo/cxt_demo0SonarA/demo0sys.pl", 
				"./srcMore/it/unibo/cxt_demo0SonarA/sysRules.pl", outEnvView,webDir, false);
 	}
 	
}
